# Generated by Django 3.0.3 on 2020-06-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='cancer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='corona',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='polio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dengue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='malaria',
            field=models.BooleanField(default=False),
        ),
    ]
